import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Nav } from "@/components/nav";
import Footer from "@/components/layout/Footer";
import { ContactFloater } from "@/components/ContactFloater";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Suppress hydration warnings for Grammarly and similar extensions
const suppressHydrationWarning = true;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={suppressHydrationWarning}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={suppressHydrationWarning}
      >
        <Nav />
        <main className="w-full pt-16">
          {children}
        </main>
        <Footer />
        <ContactFloater />
      </body>
    </html>
  );
}
